# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-19 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pclint',
            old_name='prj_url',
            new_name='project_url',
        ),
    ]
