# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20171119_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32)),
                ('build_time', models.DateTimeField(auto_now=True)),
                ('project_url', models.CharField(max_length=512)),
                ('error', models.IntegerField()),
                ('warning', models.IntegerField()),
            ],
        ),
    ]
